name: MA-CC

channels:
  - conda-forge

dependencies:
  - python=3.11
  - jupyterlab
  - ipykernel
  - requests
  - python-dotenv
  - pyyaml
  - pytest
  - numpy
  - pytorch
  - sentence-transformers
  - scikit-learn
  - pandas
  - pyarrow
  - matplotlib
  - tqdm
