name: MA-CC

channels:
  - conda-forge

dependencies:
  - python=3.11
  - jupyterlab
  - ipykernel
  - requests
  - openai
  - python-dotenv
  - pyyaml
  - pytest
  - numpy
  - pytorch
  - torchvision
  - accelerate
  - huggingface_hub
  - safetensors
  - transformers>=5.5
  - sentence-transformers
  - scikit-learn
  - pandas
  - pyarrow
  - matplotlib
  - tqdm
  - pip
  - pip:
      - comet_ml>=3.58,<4
