"""Relational reasoning imitation with one controller decision per round."""

from .controller import (
    CONTROLLER_EVIDENCE_STRATEGIES,
    EVIDENCE_NEUTRAL,
    EVIDENCE_STRATEGIC,
    MESSAGE_MODES,
    RECOMMENDATION_ONLY,
    RECOMMENDATION_PLUS_FACT,
    SCHEDULE_ALWAYS,
    SCHEDULE_NEVER,
    SCHEDULE_SOFT,
    RelationalRoundBudgetedControl,
    create_relational_round_budgeted_control,
)
from .game import RelationalImitationRoundFeedbackGame
from .metrics import knowledge_observables, supporting_fact_coverage
from .prompts import (
    RECEIVER_EPISTEMIC_DISPOSITIONS,
    SOCIAL_ENVIRONMENT,
    epistemic_framing,
    agent_label,
    build_relational_ballot_prompt,
    control_label,
    parse_relational_ballot,
    relational_public_ballot_prompt,
    render_control_reason,
    render_social_source,
)
from .runtime import (
    CONTROL_SOURCE_ID,
    RelationalGameResult,
    apply_epistemic_persistence,
    build_social_sources,
    run_relational_imitation_round_feedback_game,
    run_relational_imitation_round_feedback_game_sync,
    sample_controlled_positions,
)
from .state import (
    ACTIVE_FACT_IDS,
    GAME_TYPE,
    RelationalAgentState,
    RelationalGameState,
    RelationalRoundRecord,
    RelationalRules,
    RelationalTransition,
    reasoning_fact_ids,
)

__all__ = [
    "ACTIVE_FACT_IDS",
    "CONTROL_SOURCE_ID",
    "CONTROLLER_EVIDENCE_STRATEGIES",
    "EVIDENCE_NEUTRAL",
    "EVIDENCE_STRATEGIC",
    "RECEIVER_EPISTEMIC_DISPOSITIONS",
    "GAME_TYPE",
    "MESSAGE_MODES",
    "RECOMMENDATION_ONLY",
    "RECOMMENDATION_PLUS_FACT",
    "SCHEDULE_ALWAYS",
    "SCHEDULE_NEVER",
    "SCHEDULE_SOFT",
    "SOCIAL_ENVIRONMENT",
    "RelationalAgentState",
    "RelationalGameResult",
    "RelationalGameState",
    "RelationalImitationRoundFeedbackGame",
    "RelationalRoundBudgetedControl",
    "RelationalRoundRecord",
    "RelationalRules",
    "RelationalTransition",
    "agent_label",
    "apply_epistemic_persistence",
    "build_relational_ballot_prompt",
    "build_social_sources",
    "control_label",
    "create_relational_round_budgeted_control",
    "epistemic_framing",
    "knowledge_observables",
    "parse_relational_ballot",
    "relational_public_ballot_prompt",
    "render_control_reason",
    "render_social_source",
    "reasoning_fact_ids",
    "run_relational_imitation_round_feedback_game",
    "run_relational_imitation_round_feedback_game_sync",
    "sample_controlled_positions",
    "supporting_fact_coverage",
]
