"""Composable, cross-game scientific metrics (mas_cc Phase 8.0, trimmed design)."""

from .aggregate import (
    FORWARD_FILL_MODES,
    AggregateMetric,
    AggregateResult,
    AggregationPolicy,
    CellId,
    Curve,
    EpisodeFrame,
    SweepMetric,
    SweepResult,
    active_fraction_curve,
    aggregate_cell,
    align,
    band_curve,
    percentile,
    read_cell_episodes,
    read_episode_frame,
    rolling_within,
    sweep_over_cells,
    winner_ranking,
)
from .base import SCOPES, FinalMetric, Metric, MetricKey, StreamingMetric
from .cell import (
    CELL_METRICS,
    ActionShareRelabelled,
    ActiveFraction,
    ConsensusRound,
    ConvergedFraction,
    DominantActionShare,
    MacrostateCounts,
    create_cell_metrics,
)
from .generic import (
    ActionSharePerOption,
    AgentAbsoluteError,
    AgentCurrentValue,
    DominantValueShare,
    FirstConsensusTime,
    MeanAbsoluteError,
    RoundView,
)
from .plotting import CellProgress, grid_progress_figure, plot_cell_curves, plot_streaming_metrics
from .rolling import (
    ConsensusFlipBySuccessRate,
    RollingActionSharePerOption,
    RollingCoordinationRate,
)
from .sweep import (
    SWEEP_METRICS,
    LaggedConditionalMutualInformation,
    MutualInformationGroundTruthGap,
    MutualInformationNullBand,
    TerminalMutualInformation,
    create_sweep_metrics,
)

__all__ = [
    "CELL_METRICS",
    "FORWARD_FILL_MODES",
    "SCOPES",
    "SWEEP_METRICS",
    "ActionShareRelabelled",
    "ActionSharePerOption",
    "ActiveFraction",
    "AgentAbsoluteError",
    "AgentCurrentValue",
    "AggregateMetric",
    "AggregateResult",
    "AggregationPolicy",
    "CellId",
    "CellProgress",
    "ConsensusFlipBySuccessRate",
    "ConsensusRound",
    "ConvergedFraction",
    "Curve",
    "DominantActionShare",
    "DominantValueShare",
    "EpisodeFrame",
    "FinalMetric",
    "FirstConsensusTime",
    "LaggedConditionalMutualInformation",
    "MacrostateCounts",
    "MeanAbsoluteError",
    "Metric",
    "MetricKey",
    "MutualInformationGroundTruthGap",
    "MutualInformationNullBand",
    "RollingActionSharePerOption",
    "RollingCoordinationRate",
    "RoundView",
    "StreamingMetric",
    "SweepMetric",
    "SweepResult",
    "TerminalMutualInformation",
    "active_fraction_curve",
    "aggregate_cell",
    "align",
    "band_curve",
    "create_cell_metrics",
    "create_sweep_metrics",
    "grid_progress_figure",
    "percentile",
    "plot_cell_curves",
    "plot_streaming_metrics",
    "read_cell_episodes",
    "read_episode_frame",
    "rolling_within",
    "sweep_over_cells",
    "winner_ranking",
]
